server:
  port: 8090

#日志信息
logging:
  config: classpath:logback.xml
  level:
    #开发期间打印sql 级别是debug
    com.partner.dao: debug

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/partner_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接池
      initial-size: 5
      #连接池最小
      min-idle: 5
      #最大
      max-active: 30
      #检测关闭空闲连接 单位 hs
      time-between-eviction-runs-millis: 60000
      #去掉后 . 监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      #html 跳转
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#  mvc:
#    static-path-pattern: /static/**

  # MyBatis
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.partner.entity
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  #configLocation: classpath:mapper/mybatis-config.xml
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.partner.entity
  global-config:
    id-type: 0